stages:
  - staging
  - production
build_image_staging:
  stage: staging
  script:
    - current=$(kubectl describe deployment privateland-staging -n privateland | grep Image | awk '{print $2}' | cut -f 2 -d ':')
    - echo $current > versions
    - version=$(perl -pe 's/^((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e' < versions)
    - echo $version
    - docker info
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - docker build -t privateland:$version .
    - docker tag privateland:$version 657354073878.dkr.ecr.eu-west-1.amazonaws.com/privateland:$version
    - docker push 657354073878.dkr.ecr.eu-west-1.amazonaws.com/privateland:$version
    - kubectl set image deployment.v1.apps/privateland-staging -n privateland privateland-staging=657354073878.dkr.ecr.eu-west-1.amazonaws.com/privateland:$version --record
  tags:
    - privateland-k8s
  only:
    - staging
build_image_production:
    stage: production
    script:
    - version=$(kubectl describe deployment privateland-staging -n privateland | grep Image | awk '{print $2}' | cut -f 2 -d ':')
    - echo $version
    - echo "Deploying to production"
    - kubectl set image deployment.v1.apps/privateland -n privateland privateland=657354073878.dkr.ecr.eu-west-1.amazonaws.com/zenland:$version --record
    tags:
    - privateland-k8s
    only:
    - master