const fs = require("fs")

module.exports = (req, res, next) => {
    let list = {
        "AF": req.gettext("Afghanistan"),
        "AX": req.gettext("Åland Islands"),
        "AL": req.gettext("Albania"),
        "DZ": req.gettext("Algeria"),
        "AS": req.gettext("American Samoa"),
        "AD": req.gettext("Andorra"),
        "AO": req.gettext("Angola"),
        "AI": req.gettext("Anguilla"),
        "AQ": req.gettext("Antarctica"),
        "AG": req.gettext("Antigua and Barbuda"),
        "AR": req.gettext("Argentina"),
        "AM": req.gettext("Armenia"),
        "AW": req.gettext("Aruba"),
        "AU": req.gettext("Australia"),
        "AT": req.gettext("Austria"),
        "AZ": req.gettext("Azerbaijan"),
        "BS": req.gettext("Bahamas"),
        "BH": req.gettext("Bahrain"),
        "BD": req.gettext("Bangladesh"),
        "BB": req.gettext("Barbados"),
        "BY": req.gettext("Belarus"),
        "BE": req.gettext("Belgium"),
        "BZ": req.gettext("Belize"),
        "BJ": req.gettext("Benin"),
        "BM": req.gettext("Bermuda"),
        "BT": req.gettext("Bhutan"),
        "BO": req.gettext("Bolivia"),
        "BQ": req.gettext("Caribbean Netherlands"),
        "BA": req.gettext("Bosnia and Herzegovina"),
        "BW": req.gettext("Botswana"),
        "BV": req.gettext("Bouvet Island"),
        "BR": req.gettext("Brazil"),
        "IO": req.gettext("British Indian Ocean Territory"),
        "BN": req.gettext("Brunei Darussalam"),
        "BG": req.gettext("Bulgaria"),
        "BF": req.gettext("Burkina Faso"),
        "BI": req.gettext("Burundi"),
        "CV": req.gettext("Cabo Verde"),
        "KH": req.gettext("Cambodia"),
        "CM": req.gettext("Cameroon"),
        "CA": req.gettext("Canada"),
        "KY": req.gettext("Cayman Islands"),
        "CF": req.gettext("Central African Republic"),
        "TD": req.gettext("Chad"),
        "CL": req.gettext("Chile"),
        "CN": req.gettext("China"),
        "CX": req.gettext("Christmas Island"),
        "CC": req.gettext("Cocos (Keeling) Islands"),
        "CO": req.gettext("Colombia"),
        "KM": req.gettext("Comoros"),
        "CG": req.gettext("Congo"),
        "CD": req.gettext("Democratic Republic of the Congo"),
        "CK": req.gettext("Cook Islands"),
        "CR": req.gettext("Costa Rica"),
        "CI": req.gettext("Côte d'Ivoire"),
        "HR": req.gettext("Croatia"),
        "CU": req.gettext("Cuba"),
        "CW": req.gettext("Curaçao"),
        "CY": req.gettext("Cyprus"),
        "CZ": req.gettext("Czechia"),
        "DK": req.gettext("Denmark"),
        "DJ": req.gettext("Djibouti"),
        "DM": req.gettext("Dominica"),
        "DO": req.gettext("Dominican Republic"),
        "EC": req.gettext("Ecuador"),
        "EG": req.gettext("Egypt"),
        "SV": req.gettext("El Salvador"),
        "GQ": req.gettext("Equatorial Guinea"),
        "ER": req.gettext("Eritrea"),
        "EE": req.gettext("Estonia"),
        "SZ": req.gettext("Eswatini"),
        "ET": req.gettext("Ethiopia"),
        "FK": req.gettext("Falkland Islands (Malvinas)"),
        "FO": req.gettext("Faroe Islands"),
        "FJ": req.gettext("Fiji"),
        "FI": req.gettext("Finland"),
        "FR": req.gettext("France"),
        "GF": req.gettext("French Guiana"),
        "PF": req.gettext("French Polynesia"),
        "TF": req.gettext("French Southern Territories"),
        "GA": req.gettext("Gabon"),
        "GM": req.gettext("Gambia"),
        "GE": req.gettext("Georgia"),
        "DE": req.gettext("Germany"),
        "GH": req.gettext("Ghana"),
        "GI": req.gettext("Gibraltar"),
        "GR": req.gettext("Greece"),
        "GL": req.gettext("Greenland"),
        "GD": req.gettext("Grenada"),
        "GP": req.gettext("Guadeloupe"),
        "GU": req.gettext("Guam"),
        "GT": req.gettext("Guatemala"),
        "GG": req.gettext("Guernsey"),
        "GN": req.gettext("Guinea"),
        "GW": req.gettext("Guinea-Bissau"),
        "GY": req.gettext("Guyana"),
        "HT": req.gettext("Haiti"),
        "HM": req.gettext("Heard Island and McDonald Islands"),
        "VA": req.gettext("Holy See"),
        "HN": req.gettext("Honduras"),
        "HK": req.gettext("Hong Kong"),
        "HU": req.gettext("Hungary"),
        "IS": req.gettext("Iceland"),
        "IN": req.gettext("India"),
        "ID": req.gettext("Indonesia"),
        "IR": req.gettext("Iran"),
        "IQ": req.gettext("Iraq"),
        "IE": req.gettext("Ireland"),
        "IM": req.gettext("Isle of Man"),
        "IL": req.gettext("Israel"),
        "IT": req.gettext("Italy"),
        "JM": req.gettext("Jamaica"),
        "JP": req.gettext("Japan"),
        "JE": req.gettext("Jersey"),
        "JO": req.gettext("Jordan"),
        "KZ": req.gettext("Kazakhstan"),
        "KE": req.gettext("Kenya"),
        "KI": req.gettext("Kiribati"),
        "KP": req.gettext("North Korea"),
        "KR": req.gettext("South Korea"),
        "KW": req.gettext("Kuwait"),
        "KG": req.gettext("Kyrgyzstan"),
        "LA": req.gettext("Laos"),
        "LV": req.gettext("Latvia"),
        "LB": req.gettext("Lebanon"),
        "LS": req.gettext("Lesotho"),
        "LR": req.gettext("Liberia"),
        "LY": req.gettext("Libya"),
        "LI": req.gettext("Liechtenstein"),
        "LT": req.gettext("Lithuania"),
        "LU": req.gettext("Luxembourg"),
        "MO": req.gettext("Macao"),
        "MG": req.gettext("Madagascar"),
        "MW": req.gettext("Malawi"),
        "MY": req.gettext("Malaysia"),
        "MV": req.gettext("Maldives"),
        "ML": req.gettext("Mali"),
        "MT": req.gettext("Malta"),
        "MH": req.gettext("Marshall Islands"),
        "MQ": req.gettext("Martinique"),
        "MR": req.gettext("Mauritania"),
        "MU": req.gettext("Mauritius"),
        "YT": req.gettext("Mayotte"),
        "MX": req.gettext("Mexico"),
        "FM": req.gettext("Federated States of Micronesia"),
        "MD": req.gettext("Moldova"),
        "MC": req.gettext("Monaco"),
        "MN": req.gettext("Mongolia"),
        "ME": req.gettext("Montenegro"),
        "MS": req.gettext("Montserrat"),
        "MA": req.gettext("Morocco"),
        "MZ": req.gettext("Mozambique"),
        "MM": req.gettext("Myanmar"),
        "NA": req.gettext("Namibia"),
        "NR": req.gettext("Nauru"),
        "NP": req.gettext("Nepal"),
        "NL": req.gettext("Netherlands"),
        "NC": req.gettext("New Caledonia"),
        "NZ": req.gettext("New Zealand"),
        "NI": req.gettext("Nicaragua"),
        "NE": req.gettext("Niger"),
        "NG": req.gettext("Nigeria"),
        "NU": req.gettext("Niue"),
        "NF": req.gettext("Norfolk Island"),
        "MK": req.gettext("North Macedonia"),
        "MP": req.gettext("Northern Mariana Islands"),
        "NO": req.gettext("Norway"),
        "OM": req.gettext("Oman"),
        "PK": req.gettext("Pakistan"),
        "PW": req.gettext("Palau"),
        "PS": req.gettext("Palestine"),
        "PA": req.gettext("Panama"),
        "PG": req.gettext("Papua New Guinea"),
        "PY": req.gettext("Paraguay"),
        "PE": req.gettext("Peru"),
        "PH": req.gettext("Philippines"),
        "PN": req.gettext("Pitcairn"),
        "PL": req.gettext("Poland"),
        "PT": req.gettext("Portugal"),
        "PR": req.gettext("Puerto Rico"),
        "QA": req.gettext("Qatar"),
        "RE": req.gettext("Réunion"),
        "RO": req.gettext("Romania"),
        "RU": req.gettext("Russia"),
        "RW": req.gettext("Rwanda"),
        "BL": req.gettext("Saint Barthélemy"),
        "SH": req.gettext("Saint Helena, Ascension and Tristan da Cunha"),
        "KN": req.gettext("Saint Kitts and Nevis"),
        "LC": req.gettext("Saint Lucia"),
        "MF": req.gettext("Saint Martin (French part)"),
        "PM": req.gettext("Saint Pierre and Miquelon"),
        "VC": req.gettext("Saint Vincent and the Grenadines"),
        "WS": req.gettext("Samoa"),
        "SM": req.gettext("San Marino"),
        "ST": req.gettext("Sao Tome and Principe"),
        "SA": req.gettext("Saudi Arabia"),
        "SN": req.gettext("Senegal"),
        "RS": req.gettext("Serbia"),
        "SC": req.gettext("Seychelles"),
        "SL": req.gettext("Sierra Leone"),
        "SG": req.gettext("Singapore"),
        "SX": req.gettext("Sint Maarten (Dutch part)"),
        "SK": req.gettext("Slovakia"),
        "SI": req.gettext("Slovenia"),
        "SB": req.gettext("Solomon Islands"),
        "SO": req.gettext("Somalia"),
        "ZA": req.gettext("South Africa"),
        "GS": req.gettext("South Georgia and the South Sandwich Islands"),
        "SS": req.gettext("South Sudan"),
        "ES": req.gettext("Spain"),
        "LK": req.gettext("Sri Lanka"),
        "SD": req.gettext("Sudan"),
        "SR": req.gettext("Suriname"),
        "SJ": req.gettext("Svalbard and Jan Mayen"),
        "SE": req.gettext("Sweden"),
        "CH": req.gettext("Switzerland"),
        "SY": req.gettext("Syria"),
        "TW": req.gettext("Taiwan, Province of China"),
        "TJ": req.gettext("Tajikistan"),
        "TZ": req.gettext("Tanzania"),
        "TH": req.gettext("Thailand"),
        "TL": req.gettext("Timor-Leste"),
        "TG": req.gettext("Togo"),
        "TK": req.gettext("Tokelau"),
        "TO": req.gettext("Tonga"),
        "TT": req.gettext("Trinidad and Tobago"),
        "TN": req.gettext("Tunisia"),
        "TR": req.gettext("Turkey"),
        "TM": req.gettext("Turkmenistan"),
        "TC": req.gettext("Turks and Caicos Islands"),
        "TV": req.gettext("Tuvalu"),
        "UG": req.gettext("Uganda"),
        "UA": req.gettext("Ukraine"),
        "AE": req.gettext("the United Arab Emirates"),
        "GB": req.gettext("the United Kingdom"),
        "UK": req.gettext("the United Kingdom"),
        "US": req.gettext("the United States"),
        "UM": req.gettext("the United States Minor Outlying Islands"),
        "UY": req.gettext("Uruguay"),
        "UZ": req.gettext("Uzbekistan"),
        "VU": req.gettext("Vanuatu"),
        "VE": req.gettext("Venezuela"),
        "VN": req.gettext("Viet Nam"),
        "VG": req.gettext("Virgin Islands (British)"),
        "VI": req.gettext("Virgin Islands (U.S.)"),
        "WF": req.gettext("Wallis and Futuna"),
        "EH": req.gettext("Western Sahara"),
        "YE": req.gettext("Yemen"),
        "ZM": req.gettext("Zambia"),
        "ZW": req.gettext("Zimbabwe")
    }

    let code = req.params.geo || req.userLocation.cc || "US"
    if (!list[code.toUpperCase()]) code = req.userLocation.cc || "US"

    code = code.toUpperCase()

    res.locals.bestGeo = req.bestGeo = {
        code: code,
        text: list[code]
    }
    next()

}